parameters:
#    application_prism_poll.example.class: Application\Prism\PollBundle\Example

services:
#    application_prism_poll.example:
#        class: %application_prism_poll.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
